### ISSUE TITLE
Create Vagrantfile

### ISSUE THREAD

**Issue by rgordon126** [nyu-devops-team7/shopcarts#1]
**As a:** developer
**I need:** a consistent virtual environment
**So that:** so that I (and my team) can start writing code from day one

**Assumptions:** 

- We will be using VirtualBox, Vagrant, and Docker
- We will be using Linux (Ubuntu Linux 20.04)
- The environment should have Python 3.8, Flask 1.1.1 provisioned

**Acceptance Criteria:**
*Given* the developer has access to the Vagrantfile
*When* a developer uses the `vagrant up` command
*Then* the virtual machine should be online and active

*Given* they are in the virtual environment
*When* a developer runs the `vagrant ssh` command
*Then* they should access the virtual machine

*Given* a developer is in the virtual machine
*When* the developer uses the `docker images` command
*Then* they should see Postgres is installed

**Comment by prateeksab** [comment]
hey guys - this tutorial will be useful as you setup vagrant environment - https://www.youtube.com/watch?v=vBreXjkizgo
