### ISSUE TITLE
Read products & quantities in shopcart

### ISSUE THREAD

**Issue by rgordon126** [nyu-devops-team7/shopcarts#2]
**As a:** customer
**I need:** to be able to read the complete list of the products, their quantities, and their total price that are currently in shopcart
**So that:** I know what items, how many items, and what cost I am about to purchase/incur

**Assumptions:** 
- The shopcart is list of items a customer intends to purchase
- For each product line, total quantity and total cost should be indicated
- Price will be in **USD** and **not** include tax
- Items added to the shopcart appear in chronological order (the first item added to the shopcart appears at the top of the list and the last item added appears at the bottom of the list)

**Acceptance Criteria:**
*Given* an item was added to the shopcart
*When* the customer views the shopcart
*Then* the customer must be able to see the product's name, quantity, and total price in the shopcart

**Comment by prateeksab** [comment]
@rgordon126 - looks good to me. will create one for updating/deleting the items in the cart
