### ISSUE TITLE
Set up cloud environment & service

### ISSUE THREAD

**Issue by rlbgreenberg** [nyu-devops-team7/shopcarts#25]
**As a:** developer
**I need:** an IBM Cloud account with a working Cloud service
**So that:** to be able to deploy the application to the cloud

**Assumptions:** 
- Using IBM Cloud
- File name is: `nyu-shopcart-service-f21`

**Acceptance Criteria:**
*Given* I'm logged into IBM cloud
*When* I search for created services
*Then* I will see that `nyu-shopcart-service-f21.us-south.cf.appdomain.cloud` is created and active

**Comment by rgordon126** [comment]
Active. [See the live link.](https://nyu-shopcart-service-f21.us-south.cf.appdomain.cloud/)
