### ISSUE TITLE
Add honcho and ensure application works in cloud

### ISSUE THREAD

**Issue by higuchihisao** [nyu-devops-team7/shopcarts#27]
**As a:** developer
**I need:** to add honcho to the `requirements.txt` file
**So that:** the shopcarts application starts in the IBM Cloud

**Assumptions:** 
- Working with IBM Cloud

**Acceptance Criteria:**
*Given* that I'm in the Vagrant VM
*When* I execute `honcho start` and there are no errors
*Then* the honcho file successfully works with our `Procfile`

*Given* that I'm in the Vagrant VM
*When* I execute `ibmcloud cf push`
*Then* the application is successfully pushed to IBM Cloud

**Comment by prateeksab** [comment]
to be revised after class on 3/31
