### ISSUE TITLE
Deploy application to Cloud And have ability to run it locally

### ISSUE THREAD

**Issue by prateeksab** [nyu-devops-team7/shopcarts#29]
**As a:**  developer
**I need:** to ensure the VM can connect to the cloud
**So that:** the application can be deployed and can run on the cloud

**To Dos:** 

- Vagrant file needs to be updated with IBM Cloud settings
- Need to create  manifest.yml, ProcFile, runtime.tst files
- Modify VCAP_SERVICES environment variable
- Add Honcho to requirements.txt

**Acceptance Criteria:**

*Given* Cloud foundry metadata files are created 
*When* when we run the command ibmcloud cd push to deploy the application
*Then* the application is deployed to cloud and accessible via the URL of the service

*Given* Honcho is installed
*When* we run the command honcho start
*Then* the application is deployed locally to a prod server

**Comment by rgordon126** [comment]
To be updated after class on 3/31

**Comment by prateeksab** [comment]
@rgordon126 - 
I updated .cfignore, .env, manifest.yml files

Waiting on the url for the following -
.travis.yml

Check the cloudIntegration  branch
