### ISSUE TITLE
Delete product from shopcart

### ISSUE THREAD

**Issue by ora11** [nyu-devops-team7/shopcarts#4]
**As a:** customer 
**I need:** to be able to remove (delete) products that were previously added to my shopcart
**So that:** I don't buy items I don't want to purchase

**Assumptions:** 
- There should be a delete button for each product line in the shopcart

**Acceptance Criteria:**
*Given* an item is deleted from the shopcart
*When* the customer views the shopcart
*Then* the item is no longer listed

**Comment by prateeksab** [comment]
@ora11 - Looks good to me
