### ISSUE TITLE
Modify the products in the cart

### ISSUE THREAD

**Issue by prateeksab** [nyu-devops-team7/shopcarts#5]
**As a:** customer
**I need:** to be able to modify the quantities of the products
**So that:** I can checkout with my correct and final order

**Assumptions:** 
- There will be functionality to change the number of products to an integer from 1 to 10

**Acceptance Criteria:**
*Given:* a customer is viewing his/her/their shopcart
*When:* they increase/decrease the quantity of products in the shopcart
*Then:* the accurate quantity and cost total is reflected in the updated shopcart

**Comment by prateeksab** [comment]
@ora11 - I am modifying this issue to remove delete products ..will change it to only update the quantity

**Comment by rgordon126** [comment]
@prateeksab -- you first AC reads a bit weird. Given a customer does what... navigates to their shopcart? is viewing their shopcart? GIVEN applies some current state or page. WHEN applies some action to that state. THEN applies the expected response to the state + action
