### ISSUE TITLE
Create a shopcart skeleton app

### ISSUE THREAD

**Issue by prateeksab** [nyu-devops-team7/shopcarts#6]
**As a:** customer 
**I need:** a shopcart 
**So that:** I can see all the products I want to buy before I actually purchase them 

**Assumptions:** 

- Customers can buy any product at any quantity
- Each customer has one unique shopcart
- Customers only have access to their cart and no other carts
- We will be using a Postgres database to manage and link: customers, products, shopcarts
- We will be using Flask to set up the foundational elements of the skeleton app

**Acceptance Criteria:**
*Given:* a customer visits our website
*When:* they navigate to their shopcart
*Then:* they should be taken to their shopcart

*Given:* a shopping cart is empty
*When:* a customer navigates their shopcart
*Then:* they should see an empty shopcart

**Comment by prateeksab** [comment]
@rgordon126 @ora11 @rlbgreenberg - was having a hardtime coming up with the acceptance criteria.
Trying to solve #2 - Create a skeleton App
All feedback is welcome, feel free to edit

**Comment by rgordon126** [comment]
@prateeksab -- made some edits. this could also be from the developer perspective... need to think about it a bit more
