### ISSUE TITLE
Create shopcart database

### ISSUE THREAD

**Issue by rlbgreenberg** [nyu-devops-team7/shopcarts#8]
**As a:** developer
**I need:** a database for shopcarts
**So that:** the microservice can hold data and run effectively

**Assumptions:** 
- The fields of a shopcart include customer_id (int), product_id (int), product_name (varchar(40)), product_quantity_in_cart (int), product_price (float)
- The total price of the shopcart will be dynamically calculated and does not need to be a column
- We will use Postgres and name the database shopcarts_data

**Acceptance Criteria:**
*Given* I'm a developer logged into the database
*When* I run the command `describe shopcarts_data`
*Then* I should see the fields and correct datatypes specified above

**Comment by rgordon126** [comment]
Great start, @rlbgreenberg! Added some comments!
